import { Fleur_De_Leah } from "next/font/google";
import "./globals.css";

const fleurDeLeah = Fleur_De_Leah({
  weight: "400",
  variable: "--font-fleur-de-leah",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${fleurDeLeah.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
